"""Database Models Migration

Revision ID: 1f71321253ac
Revises: 
Create Date: 2023-09-01 17:29:57.514771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f71321253ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_medicalarticle', sa.Column('saved_medicalarticle_id', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_medicalarticle', 'saved_medicalarticle_id')
    # ### end Alembic commands ###
