"""Database Migration

Revision ID: 77d0fab5a17b
Revises: 7fd7fc88664e
Create Date: 2023-08-24 03:30:51.626551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d0fab5a17b'
down_revision: Union[str, None] = '7fd7fc88664e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalarticle', sa.Column('query_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicalarticle', 'query_count')
    # ### end Alembic commands ###
