"""Database Models Migration

Revision ID: a1ebbd117af2
Revises: 6862e92e2feb
Create Date: 2023-09-17 17:45:50.626641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ebbd117af2'
down_revision: Union[str, None] = '6862e92e2feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('image', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'image')
    # ### end Alembic commands ###
