name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shutdown Default MySQL
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host_port: 3800
          container_port: 3307
          character_set_server: 'utf8'
          collation_server: 'utf8_general_ci'
          mysql_version: '8.0'
          mysql_database: 'MedInfoPlus_test_db'
          mysql_root_password: ${{ secrets.ROOTPASSWORD }}
          mysql_user: 'MedInfoPlus_test'
          mysql_password: ${{ secrets.MEDINFOPLUS_MYSQL_TEST_PWD }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "MedInfoPlus_MYSQL_USER=MedInfoPlus_test" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_PWD=MedInfoPlus_test_pwd" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_HOST=localhost" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_DB=MedInfoPlus_test_db" >> $GITHUB_ENV
          echo "MedInfoPlus_ENV=test" >> $GITHUB_ENV

      - name: Install MySQL Client Library
        run: |
          pip install mysqlclient

      - name: Show MedInfoPlus_ENV variable
        run: |
          printenv | grep MedInfoPlus_ENV

      - name: Run BaseModel Class Tests
        run: |
          echo "BaseModel Class Tests"
          python3 -m unittest tests.test_models.test_base_model

      - name: Run MedicalArticle Class Tests
        run: |
          echo "MedicalArticle Class Tests"
          python3 -m unittest tests.test_models.test_medical_article

      - name: Run Resource Class Tests
        run: |
          echo "Resource Class Tests"
          python3 -m unittest tests.test_models.test_resource

