name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: MedInfoPlus_test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "MedInfoPlus_MYSQL_USER=$DB_USER" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_PWD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_HOST=localhost" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_DB=$DB_DATABASE" >> $GITHUB_ENV
          echo "MedInfoPlus_ENV=test" >> $GITHUB_ENV

      - name: Install MySQL Client Library
        run: |
          pip install mysqlclient

      - name: Run Unit test
        run: |
          ./Config_Management/unittest.sh
