name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: MedInfoPlus_test_user # Use a different user name
          MYSQL_PASSWORD: MedInfoPlus_test_pwd
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: MedInfoPlus_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
      - name: Start MySQL Server
        run: |
          sudo service mysql start
          systemctl status mysql.service
      - name: Check MySQL Server Status
        run: |
          sudo service mysql status
      - name: Set up MySQL for testing
        run: |
          echo "Creating MySQL database and user"
          mysql -h127.0.0.1 -uroot -proot_password -e "CREATE DATABASE IF NOT EXISTS MedInfoPlus_test_db;"
          mysql -h127.0.0.1 -uroot -proot_password -e "CREATE USER IF NOT EXISTS 'MedInfoPlus_test'@'localhost' IDENTIFIED BY 'MedInfoPlus_test_pwd';"
          mysql -h127.0.0.1 -uroot -proot_password -e "GRANT ALL PRIVILEGES ON MedInfoPlus_test_db.* TO 'MedInfoPlus_test'@'localhost';"
          mysql -h127.0.0.1 -uroot -proot_password -e "FLUSH PRIVILEGES;"
          echo "MySQL setup completed"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "MedInfoPlus_MYSQL_USER=MedInfoPlus_test" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_PWD=MedInfoPlus_test_pwd" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_HOST=localhost" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_DB=MedInfoPlus_test_db" >> $GITHUB_ENV
          echo "MedInfoPlus_ENV=test" >> $GITHUB_ENV
      - name: Install MySQL Client Library
        run: |
          pip install mysqlclient
      - name: Show MedInfoPlus_ENV variable
        run: |
          printenv | grep MedInfoPlus_ENV
      - name: Run BaseModel Class Tests
        run: |
          echo "BaseModel Class Tests"
          python3 -m unittest tests.test_models.test_base_model
      - name: Run MedicalArticle Class Tests
        run: |
          echo "MedicalArticle Class Tests"
          python3 -m unittest tests.test_models.test_medical_article
      - name: Run Resource Class Tests
        run: |
          echo "Resource Class Tests"
          python3 -m unittest tests.test_models.test_resource
