name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL for testing
        run: |
          echo "Creating MySQL database and user"
          cat Config_Management/setup_mysql_test.sql | mysql -h127.0.0.1 -uroot -proot_password
          echo "MySQL setup completed"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "MedInfoPlus_MYSQL_USER=MedInfoPlus_test" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_PWD=${{ secrets.MEDINFOPLUS_MYSQL_TEST_PWD }}" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_HOST=mysql" >> $GITHUB_ENV
          echo "MedInfoPlus_MYSQL_DB=MedInfoPlus_test_db" >> $GITHUB_ENV
          echo "MedInfoPlus_ENV=test" >> $GITHUB_ENV

      - name: Install MySQL Client Library
        run: |
          pip install mysqlclient

      - name: Run SQLAlchemy model tests
        run: ./Config_Management/unittest.sh
